### PR TITLE
fixed positions in all uses.csv

### PR DESCRIPTION
**Pull request by roksanagow**

### CODE REVIEW

**Comment by akutuzov** [comment]
Thanks for the pull request!

But can you please address these two issues before it is merged:

1.  This PR changes many more lines than needed, making it difficult to sanity-check the actual changes in position indices. This is because when saving tab-separated files, you use the default `Pandas` setting of `csv.QUOTE_MINIMAL`, thus introducing additional quotation marks in enormous number of lines.  In RuSemShift, we don't use any quoting.  Can you please save the files with `pd.to_csv(quoting=csv.QUOTE_NONE)`?
2. It's great that you accompany the PR with your code, but may we ask you to provide it as a regular Python script (`.py`) , not as a Jupyter notebook (`.ipynb`)?

Thanks again!

**Comment by roksanagow** [comment]
Hi Andrey,

I applied the changes and cleaned up the code a bit as well to remove unnecessary lines I used in my analysis. 
Let me know if these look correct!

Kind Regards,
Roksana

**Comment by akutuzov** [comment]
Thanks, this looks much better!
Only one minor thing: I believe you should use `quoting=csv.QUOTE_NONE` also when _reading_ the files, not only when _saving_ them (`pd.read_csv("uses.csv", sep="\t", quoting=csv.QUOTE_NONE)`). Otherwise, Pandas silently removes some quotation marks, for example, [here](https://github.com/juliarodina/RuSemShift/blob/3f1a184de3d9202a7988a8441c16424e20d00956/rusemshift_2/DWUG/data/%D1%84%D0%BB%D0%B0%D0%BA%D0%BE%D0%BD/uses.csv#L2). We don't want to lose any data :)

Otherwise, everything's fine, and once the issue with the quotation marks is resolved, I will happily merge this PR.

**Comment by roksanagow** [comment]
Hi Andrej, 
Apologies for the delay, here are the files with the quoting=csv.QUOTE_NONE when both loading and saving the data! :) 

Kind Regards,
Roksana

**Comment by akutuzov** [comment]
Thanks a lot!

**Pull request merged**
